import 'privacy_policy_content.dart';

const String termsOfUseEffectiveDate = 'January 30, 2026';

const List<PolicySection> termsOfUseSections = [
  PolicySection(
    title: 'Terms of Use',
    content: '',
    isHeading: true,
  ),
  PolicySection(
    title: 'Agreement to Terms',
    content:
        'By accessing and using FlirtFix ("App"), you accept and agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the App. These terms constitute a legally binding agreement between you and FlirtFix.',
  ),
  PolicySection(
    title: '1. Service Description',
    content:
        'FlirtFix is an AI-powered mobile application that provides:\n\n• Conversation assistance and reply suggestions for dating app conversations\n\n• Screenshot analysis using optical character recognition (OCR)\n\n• Profile image analysis and opening message suggestions\n\n• Custom instruction support for personalized AI responses\n\n• Subscription-based unlimited access with fair use limits',
  ),
  PolicySection(
    title: '2. Acceptable Use Policy',
    content:
        'You agree to use FlirtFix only for lawful purposes. You may NOT:\n\n• Use the App to harass, abuse, or harm others\n\n• Submit offensive, illegal, or inappropriate content\n\n• Attempt to circumvent usage limits or fair use policies\n\n• Reverse engineer, decompile, or attempt to extract source code\n\n• Use automated systems or bots to access the App\n\n• Resell or redistribute AI-generated content commercially\n\n• Violate any applicable laws or regulations\n\n• Impersonate others or create fake accounts\n\nViolation of this policy may result in immediate account termination.',
  ),
  PolicySection(
    title: '3. Fair Use Policy',
    content:
        'Subscription plans are "unlimited" subject to fair use:\n\n• Daily limits: Applied to openers and replies to prevent abuse\n\n• Weekly limits: Additional usage caps may apply\n\n• API rate limiting: Excessive requests may be throttled\n\n• Quality over quantity: The service is intended for genuine personal use\n\n• Abuse detection: Automated systems monitor for unusual patterns\n\nUsers exceeding fair use limits may have their access temporarily restricted. Persistent abuse may result in account termination without refund.',
  ),
  PolicySection(
    title: '4. Account Registration',
    content:
        'To use FlirtFix, you must:\n\n• Be at least 18 years of age\n\n• Provide accurate and complete registration information\n\n• Maintain the security of your password\n\n• Accept responsibility for all activities under your account\n\n• Notify us immediately of any unauthorized access\n\nYou may not share your account credentials or allow others to use your account.',
  ),
  PolicySection(
    title: '5. Subscription Terms',
    content:
        'FlirtFix Unlimited Subscription:\n\n• Price: \$6.99 per week, billed weekly\n\n• Payment: Processed through Google Play Billing\n\n• Auto-renewal: Subscriptions automatically renew unless canceled\n\n• Cancellation: You may cancel anytime through Google Play\n\n• No refunds: Cancellation takes effect at the end of the current billing period\n\n• Price changes: We may change subscription prices with 30 days notice\n\nCredits:\n\n• Non-refundable once purchased\n\n• Used for API calls and premium features\n\n• No expiration while account is active\n\n• Lost upon account deletion',
  ),
  PolicySection(
    title: '6. Intellectual Property Rights',
    content:
        'Content Ownership:\n\n• Your Content: You retain ownership of conversation data and images you upload\n\n• AI-Generated Content: Suggestions generated by our AI are provided for your personal use. You may use them freely in your conversations.\n\n• App Ownership: FlirtFix owns all rights to the App, including source code, design, algorithms, and branding\n\n• License Grant: You grant us a limited license to process your submitted content for the purpose of providing our services\n\n• Trademarks: "FlirtFix" and associated logos are our trademarks',
  ),
  PolicySection(
    title: '7. Disclaimer of Warranties',
    content:
        'THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND:\n\n• No Guarantee of Results: AI suggestions are guidance only, not guarantees of success\n\n• No Accuracy Warranty: We do not warrant that AI suggestions are appropriate or effective\n\n• No Uptime Guarantee: Service availability is not guaranteed\n\n• Third-Party Services: We are not responsible for dating apps or platforms you use\n\n• Your Responsibility: You are solely responsible for your communications and relationships\n\nAI-generated content should be reviewed and personalized before use. We are not responsible for outcomes of conversations.',
  ),
  PolicySection(
    title: '8. Limitation of Liability',
    content:
        'TO THE MAXIMUM EXTENT PERMITTED BY LAW:\n\n• We are not liable for indirect, incidental, special, or consequential damages\n\n• Our total liability shall not exceed the amount you paid in the last 12 months\n\n• We are not liable for:\n  - Relationship outcomes or failed connections\n  - Offensive or inappropriate AI-generated content\n  - Data loss or technical failures\n  - Third-party actions or dating platform policies\n  - Unauthorized account access due to your negligence',
  ),
  PolicySection(
    title: '9. Service Availability',
    content:
        'We strive to maintain service availability but:\n\n• Maintenance: Scheduled maintenance may cause temporary interruptions\n\n• Updates: We may update or modify features without notice\n\n• API Limits: Third-party AI service limits may affect availability\n\n• No Guarantee: We do not guarantee uninterrupted or error-free service\n\n• Right to Modify: We reserve the right to modify or discontinue features',
  ),
  PolicySection(
    title: '10. Termination',
    content:
        'We may suspend or terminate your account if:\n\n• You violate these Terms of Use\n\n• You engage in fraudulent activity or payment disputes\n\n• You exceed fair use limits persistently\n\n• Required by law or legal process\n\n• The App is discontinued\n\nUpon termination:\n\n• Your access is immediately revoked\n\n• Your data may be deleted per our retention policy\n\n• No refunds for remaining subscription time\n\n• You must cease all use of AI-generated content',
  ),
  PolicySection(
    title: '11. Governing Law and Jurisdiction',
    content:
        'These Terms are governed by and construed in accordance with the laws of the United States, without regard to conflict of law principles. You agree to submit to the exclusive jurisdiction of courts located in the United States for resolution of disputes.',
  ),
  PolicySection(
    title: '12. Dispute Resolution',
    content:
        'Before filing any legal claim:\n\n• Contact us at support@tryagaintext.com to resolve the dispute informally\n\n• Allow 30 days for good faith negotiation\n\n• If unresolved, disputes may be submitted to binding arbitration\n\n• You waive the right to participate in class action lawsuits\n\n• Small claims court remains available for eligible disputes',
  ),
  PolicySection(
    title: '13. Changes to Terms',
    content:
        'We may modify these Terms at any time:\n\n• Updates will be posted in the App with a new Effective Date\n\n• Material changes will be communicated via email\n\n• Continued use after changes constitutes acceptance\n\n• If you disagree with changes, discontinue use and cancel subscription',
  ),
  PolicySection(
    title: '14. Severability',
    content:
        'If any provision of these Terms is found unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that these Terms otherwise remain in full force and effect.',
  ),
  PolicySection(
    title: '15. Entire Agreement',
    content:
        'These Terms, together with our Privacy Policy and Refund Policy, constitute the entire agreement between you and FlirtFix regarding use of the App and supersede all prior agreements.',
  ),
  PolicySection(
    title: '16. Contact Information',
    content:
        'For questions about these Terms of Use:\n\nEmail: support@tryagaintext.com\n\nCompany: FlirtFix\n\nWe will respond to inquiries within 5 business days.',
  ),
];
